<a href="https://colab.research.google.com/github/reedburmaster/mis433/blob/main/PythonBasicsAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment: Python Basics
We assume you are using Python 3 in this course.

## Question 1

You've learned different data types in Python. Now, let's test your knowledge.

You need to use to format strings.

Write a program using the "f-strings" (https://realpython.com/python-f-strings/) and user input function to convert temperatures from Fahrenheit to Celsius. [Formula: Celsius = (Fahrenheit – 32)*5/9]

Hint: you may need int() or float() function

An example program output:
```
Please enter the temperature in Fahrenheit: 140
140F is 60.0 in Celsius.
```

In [1]:
# an example of f-strings and user input function
username = input('What\'s your name? ')
print(f'Welcome, {username}!')

What's your name? Reed
Welcome, Reed!


In [3]:
# complete your program here
f_str = input('Please enter the temperature in Fahrenheit: ')
fahrenheit = float(f_str)

#Celsius = (Fahrenheit – 32)*5/9
celsius = (fahrenheit - 32) * 5/9

print(f'{fahrenheit}F is {celsius} in Celsius.')

Please enter the temperature in Fahrenheit: 32
32.0F is 0.0 in Celsius.


Now, do the oppsoite by convert temperatures from Celsius to Fahrenheit.
Another example:
```
Please enter the temperature in Celcius: 60
60C is 140.0 in Fahrenheit.
```

In [71]:
# complete your program here
c_str = input('Please enter the temperature in Celsius: ')
celsius = float(c_str)

# Fahrenheit = (Celsius * 9/5) + 32
fahrenheit = (celsius * 9/5) + 32

f'{celsius}C is {fahrenheit} in Fahrenheit.'

Please enter the temperature in Celsius: 87


'87.0C is 188.6 in Fahrenheit.'

Next, let's make it a bit challenging by adding conditional statements to convert temperatures to and from Celsius, Fahrenheit. [Formula: Celsius/5 = (Fahrenheit – 32)/9]

An example program output:
```
Please enter the temperature: 60
Is this in Celsius or Fahrenheit? C
60C is 140 in Fahrenheit
```

Another example:
```
Please enter the temperature: 140
Is this Celsius or Fahrenheit? F
140F is 60 in Celsius
```

In [5]:
# complete your program here
d = input('Please enter the temperature: ')
m = input('Is this in Celsius or Fahrenheit? ')

temp = float(d)

if m.upper() == 'C':
    fahrenheit = (temp * 9/5) + 32
    print(f'{temp}C is {fahrenheit} in Fahrenheit.')
elif m.upper() == 'F':
    celsius = (temp - 32) * 5/9
    print(f'{temp}F is {celsius} in Celsius.')
else:
    print('Invalid unit. Please enter C or F.')

Please enter the temperature: 32
Is this in Celsius or Fahrenheit? F
32.0F is 0.0 in Celsius.


## Question 2

Have some fun with strings.

In [6]:
sentence = "Talk is cheap. Show me the code - Linus Torvalds"

In [13]:
# Find the length of this sentence.
len(sentence)

48

In [14]:
# Convert the whole string to lower case.
sentence.lower()

'talk is cheap. show me the code - linus torvalds'

In [15]:
# Extract a substring from the 10th character from left to the 10th character from right.
sentence[9:-9]

'heap. Show me the code - Linus'

In [16]:
# Split the sentence into a list of substrings by space ' '.
sentence.split(' ')


['Talk', 'is', 'cheap.', 'Show', 'me', 'the', 'code', '-', 'Linus', 'Torvalds']

In [17]:
# Given the sentence, output a list of words in lowercase (without punctuations).
sentence.lower().replace('.','').replace('-','')

'talk is cheap show me the code  linus torvalds'

In [20]:
# Count the total number of vowels in the sentence.
vowels = 'aeiou'
vowel_count = 0
for char in sentence.lower():
    if char in vowels:
        vowel_count += 1
f'Total number of vowels: {vowel_count}'

'Total number of vowels: 13'

In [19]:
# Find the positions (indexes) of all vowels in the sentence.
vowels = 'aeiou'
vowel_indexes = []
for i in range(len(sentence)):
    if sentence[i].lower() in vowels:
        vowel_indexes.append(i)
f'Positions of vowels: {vowel_indexes}'

'Positions of vowels: [1, 5, 10, 11, 17, 21, 25, 28, 30, 35, 37, 41, 44]'

## Question 3

Review list comprehension if needed: https://realpython.com/list-comprehension-python/

The formula for list comprehension is: `new_list = [expression for member in iterable (if conditional)]`

You need to do the following:

In [22]:
# Use a loop to create a list of 5 cube numbers and print the list：[0, 1, 8, 27, 64]
cubes = []
for i in range(5):
    cubes.append(i**3)
cubes

[0, 1, 8, 27, 64]

In [24]:
# Use list comprehension to create the same list
cubes_lc = [i**3 for i in range(5)]
cubes_lc

[0, 1, 8, 27, 64]

In [27]:
# Find the postions (indexes) of all vowels in a sentence using list comprehension
sentence = "Toto, I\'ve a feeling we\'re not in Kansas anymore. - THE WIZARD OF OZ (1939)"

vowel_indexes_lc = [i for i, char in enumerate(sentence.lower()) if char in vowels]
f'Positions of vowels: {vowel_indexes_lc}'

'Positions of vowels: [1, 3, 6, 9, 11, 14, 15, 17, 22, 25, 28, 31, 35, 38, 41, 45, 47, 54, 57, 59, 63, 66]'

In [30]:
# Use a loop to create a list of first n numbers in the Fibonacci sequence
# [0, 1, 1, 2, 3, 5, 8, ...]
fibonacci = []
n_str = input('n = ')
n = int(n_str)

if n <= 0:
    fibonacci = []
elif n == 1:
    fibonacci = [0]
elif n == 2:
    fibonacci = [0, 1]
else:
    fibonacci = [0, 1]
    for _ in range(2, n):
        next_fib = fibonacci[-1] + fibonacci[-2]
        fibonacci.append(next_fib)

fibonacci

n = 12


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

## Question 4

This question is about Python dictionary.

|Vaccine|Efficacy|
|-----|-------|
|Pfizer|95%|
|Moderna|95%|
|AstraZeneca|72%|
|Johnson & Johnson|66%|

Source: https://www.biospace.com/article/comparing-covid-19-vaccines-pfizer-biontech-moderna-astrazeneca-oxford-j-and-j-russia-s-sputnik-v/

In [32]:
# Create a dictionary to save the data of vaccines and their efficacy. (save 95% as 0.95)
v_dict = {
    'Pfizer': 0.95,
    'Moderna': 0.95,
    'AstraZeneca': 0.72,
    'Johnson & Johnson': 0.66
}

In [33]:
v = input('Which vaccine? ')
# print the efficacy of the vaccine
if v in v_dict:
    print(f'The efficacy of {v} is {v_dict[v]*100}%')
else:
    print(f'Vaccine "{v}" not found in the dictionary.')

Which vaccine? Pfizer
The efficacy of Pfizer is 95.0%


In [38]:
# add another vaccine 'Sputnik V' with 91.4% efficacy rate to the dictionary
v_dict['Sputnik V'] = 0.914
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914,
 'Sinovac': 0.5038}

In [42]:
# add another vaccine 'Sinovac' with 50.38% efficacy rate to the dictionary
v_dict['Sinovac'] = 0.5038
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914,
 'Sinovac': 0.5038}

In [73]:
# Print vaccines with efficacy lower than 90%.
for vaccine, efficacy in v_dict.items():
    if efficacy < 0.90:
       print(f'{vaccine}: {efficacy*100:.1f}%')

AstraZeneca: 72.0%
Johnson & Johnson: 66.0%


In [43]:
#delete the Sinovac vaccine from the dictionary
del v_dict['Sinovac']
v_dict

{'Pfizer': 0.95,
 'Moderna': 0.95,
 'AstraZeneca': 0.72,
 'Johnson & Johnson': 0.66,
 'Sputnik V': 0.914}

In [45]:
#Count the occurrence of each alphabet (no space ' ') in this sentence.
sentence = 'the quick brown fox jumps over the lazy dog'

# Save the result in a dictionary
ch_dict = {}
# Use a loop to iterate all characters
for char in sentence:
    if char.isalpha(): # Check if the character is an alphabet
        char = char.lower() # Convert to lowercase to count 'A' and 'a' as same
        ch_dict[char] = ch_dict.get(char, 0) + 1

# print the dictionary
ch_dict

{'t': 2,
 'h': 2,
 'e': 3,
 'q': 1,
 'u': 2,
 'i': 1,
 'c': 1,
 'k': 1,
 'b': 1,
 'r': 2,
 'o': 4,
 'w': 1,
 'n': 1,
 'f': 1,
 'x': 1,
 'j': 1,
 'm': 1,
 'p': 1,
 's': 1,
 'v': 1,
 'l': 1,
 'a': 1,
 'z': 1,
 'y': 1,
 'd': 1,
 'g': 1}

## Quesion 5

Next, we will practice with Numpy arrays.  

In [46]:
import numpy as np

In [47]:
# create a 1-D array of first 20 positive even numbers (starting with 2)
np.arange(2, 41, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [48]:
# create a 1-D array of first 20 positive odd numbers (starting with 1)
np.arange(1, 41, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

In [49]:
# create a 10x10 array in the following format:
# first row: [0,1,...,9]
# second row: [10,11,...,19]
# ...
# tenth row: [90,91,...,99]
np.arange(100).reshape(10, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
# Create a 10x10 array of normally distributed random values
# with mean 0 and standard deviation 1
M = np.random.normal(loc=0, scale=1, size=(10, 10))
M.shape


(10, 10)

In [77]:
# Count the numbers in M with an absolute value greater than 1.
np.sum(np.abs(M) > 1)

np.int64(32)

In [52]:
# Reference: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

# Input the number of rows (input an integer >= 3)
r = input('Row count: ')

# Input the number of rows (input another integer >= 3)
c = input('column count: ')

# Hint: you may want to use the function int().

# Create a r x c array of random integers between 10 (inclusive) and 20 (exclusive).
r_val = int(r)
c_val = int(c)
arr = np.random.randint(low=10, high=20, size=(r_val, c_val))
arr

Row count: 4
column count: 6


array([[11, 13, 14, 15, 12, 11],
       [18, 17, 10, 12, 13, 13],
       [11, 10, 11, 19, 18, 14],
       [14, 16, 14, 10, 14, 16]])

In [53]:
# output the element in the first row and the third column
arr[0, 2]

np.int64(14)

In [54]:
# output the element in the second row and the last column
arr[1, -1]

np.int64(13)

In [55]:
# output the second row of the array
arr[1, :]

array([18, 17, 10, 12, 13, 13])

In [56]:
# output the second last row of the array
arr[-2, :]

array([11, 10, 11, 19, 18, 14])

In [57]:
# output the second column of the array
arr[:, 1]

array([13, 17, 10, 16])

In [58]:
# output the second last column of the array
arr[:, -2]

array([12, 13, 18, 14])

In [59]:
# output the upper-left 3x3 sub-array
arr[:3, :3]

array([[11, 13, 14],
       [18, 17, 10],
       [11, 10, 11]])

In [60]:
# output the bottom-left 3x3 sub-array
arr[-3:, :3]

array([[18, 17, 10],
       [11, 10, 11],
       [14, 16, 14]])

In [61]:
# output the upper-right 3x3 sub-array
arr[:3, -3:]

array([[15, 12, 11],
       [12, 13, 13],
       [19, 18, 14]])

In [62]:
# output the bottom-right 3x3 sub-array
arr[-3:, -3:]

array([[12, 13, 13],
       [19, 18, 14],
       [10, 14, 16]])

In [63]:
# Create a 1-D array from 1 to 50 (inclusive)
A = np.arange(1, 51)
# Reshape A to a 5x10 array in the following format:
# first row: [1,...,10]
# second row: [11,...,20]
# ...
# fifth row: [41,...,50]
A = A.reshape(5, 10)
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [64]:
# add a row [51,...,60] to A
new_row = np.arange(51, 61)
A = np.vstack([A, new_row])
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [65]:
# split the new A (6x10) to two 3x10 arrays A1 and A2
A1, A2 = np.split(A, 2, axis=0)
print('A1:', A1)
print('A2:', A2)

A1: [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
A2: [[31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [66]:
# Add 10 to each element of A
A_plus_10 = A + 10
A_plus_10

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [67]:
# Calculate the square root of each element in A
np.sqrt(A)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
        4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
        5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978,
        6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393,
        6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781],
       [7.14142843, 7.21110255, 7.28010989, 7.34846923, 7.41619849,
        7.48331477, 7.54983444, 7.61577311, 7.68114575, 7.74596669]])

In [68]:
# Above, we have created a 10x10 array M of normally distributed random values
# with mean 0 and standard deviation 1
M.shape

(10, 10)

In [69]:
# Print the mean, standard devietion of all numbers in M
print(f'Mean: {np.mean(M):.4f}')
print(f'Standard Deviation: {np.std(M):.4f}')

Mean: 0.1139
Standard Deviation: 0.8957


In [70]:
# Print the maximumn, 3rd quartile, median, 1st quartile, and minimum in M
print(f'Maximum: {np.max(M):.4f}')
print(f'3rd Quartile: {np.percentile(M, 75):.4f}')
print(f'Median: {np.median(M):.4f}')
print(f'1st Quartile: {np.percentile(M, 25):.4f}')
print(f'Minimum: {np.min(M):.4f}')

Maximum: 2.6585
3rd Quartile: 0.6235
Median: 0.1768
1st Quartile: -0.4415
Minimum: -2.1289
